#!/usr/bin/env bun
// @version 1.0.0
// scripts/handbook/build-search-index.ts
// Reads docs/search-manifest.json and generates docs/assets/search-data.js
// containing the DOCS array and LABELS object consumed by site-search.js.
//
// Vendored between intro-to-ai-harness and multi-agent-harness-handbook.
//
// Usage:
//   bun run scripts/build-search-index.ts --docs-dir docs
//   bun run scripts/build-search-index.ts                    (default: docs/)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const idx = args.indexOf("--docs-dir");
const docsDir = idx !== -1 && args[idx + 1] ? args[idx + 1] : "docs";

// ---------------------------------------------------------------------------
// Manifest types
// ---------------------------------------------------------------------------

interface ManifestPage {
  path: string;
  title: string;
  lang: string;
}

interface Manifest {
  pages: ManifestPage[];
}

// ---------------------------------------------------------------------------
// LABELS per-language templates
// ---------------------------------------------------------------------------

const LABEL_TEMPLATES: Record<string, Record<string, string>> = {
  ko: {
    placeholder: "핸드북 전체 검색 — 섹션·항목·시나리오…",
    section: "섹션",
    scenario: "시나리오",
    item: "항목",
    noResult: "결과 없음",
    hint: "return n + '개 문서 전체에서 찾아 해당 위치로 이동합니다.';",
    building: "색인 준비 중…",
  },
  en: {
    placeholder: "Search entire handbook — sections, items, scenarios…",
    section: "Section",
    scenario: "Scenario",
    item: "Item",
    noResult: "No results",
    hint: "return n + ' documents searched. Navigates to exact position.';",
    building: "Building index…",
  },
  ja: {
    placeholder: "ハンドブック全体検索 — セクション・項目・シナリオ…",
    section: "セクション",
    scenario: "シナリオ",
    item: "項目",
    noResult: "結果なし",
    hint: "return n + '文書から検索し、該当箇所に移動します。';",
    building: "インデックス準備中…",
  },
  es: {
    placeholder: "Buscar en todo el manual — secciones, elementos, escenarios…",
    section: "Sección",
    scenario: "Escenario",
    item: "Elemento",
    noResult: "Sin resultados",
    hint: "return n + ' documentos buscados. Navega a la posición exacta.';",
    building: "Construyendo índice…",
  },
};

// ---------------------------------------------------------------------------
// Generate
// ---------------------------------------------------------------------------

function generate(): void {
  const manifestPath = join(docsDir, "search-manifest.json");

  if (!existsSync(manifestPath)) {
    console.error(`build-search-index: ${manifestPath} not found`);
    process.exit(1);
  }

  const raw = readFileSync(manifestPath, "utf-8");
  const manifest: Manifest = JSON.parse(raw);

  if (!manifest.pages || !Array.isArray(manifest.pages) || manifest.pages.length === 0) {
    console.error("build-search-index: manifest has no pages");
    process.exit(1);
  }

  // Collect unique languages
  const langs = new Set<string>();
  for (const p of manifest.pages) langs.add(p.lang);

  // Generate DOCS array
  const docsEntries = manifest.pages
    .map((p) => {
      const parts = [`{ path: '${p.path}'`, `title: '${p.title}'`, `lang: '${p.lang}'`];
      return `    { ${parts.join(", ")} }`;
    })
    .join(",\n");

  // Group entries by language for readable output
  const grouped = new Map<string, ManifestPage[]>();
  for (const p of manifest.pages) {
    if (!grouped.has(p.lang)) grouped.set(p.lang, []);
    grouped.get(p.lang)!.push(p);
  }

  const groupedDocs = Array.from(grouped.entries())
    .map(([lang, pages]) => {
      const entries = pages.map((p) => `    { path: '${p.path}', title: '${p.title}', lang: '${lang}' }`).join(",\n");
      return `    /* ── ${lang.toUpperCase()} ── */\n${entries}`;
    })
    .join(",\n\n");

  // Generate LABELS object (only for languages present in manifest)
  const labelsEntries = Array.from(langs)
    .sort()
    .map((lang) => {
      const t = LABEL_TEMPLATES[lang] || LABEL_TEMPLATES.en;
      const lines = [
        `    ${lang}: {`,
        `      placeholder: '${t.placeholder}',`,
        `      section: '${t.section}', scenario: '${t.scenario}', item: '${t.item}',`,
        `      noResult: '${t.noResult}',`,
        `      hint: function(n){ ${t.hint} },`,
        `      building: '${t.building}'`,
        `    }`,
      ];
      return lines.join("\n");
    })
    .join(",\n\n");

  // Assemble output
  const output = `/* Auto-generated by build-search-index.ts — DO NOT EDIT.
   Source of truth: docs/search-manifest.json
   Regenerate with: bun run scripts/build-search-index.ts --docs-dir docs */

var SEARCH_DATA = {
  DOCS: [
${groupedDocs}
  ],

  LABELS: {
${labelsEntries}
  }
};
`;

  const outPath = join(docsDir, "assets", "search-data.js");
  writeFileSync(outPath, output, "utf-8");

  console.log(`build-search-index: generated ${outPath} (${manifest.pages.length} pages, ${langs.size} languages)`);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

if (import.meta.main) {
  generate();
}

export { generate };
