#!/usr/bin/env bun
// @version 1.0.0
// compile-tokens.ts — src/styles/tokens.json (SSOT) → src/styles/tokens.css
//
// Enforces the three-layer reference rule from docs/design.md §4:
//   primitive → semantic → component
// A semantic token may only reference a primitive; a component token may only
// reference a semantic. Anything else is a build error, not a warning — the
// whole point of the layering is that it cannot be quietly bypassed.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const stylesDir = join(here, '..', 'src', 'styles');

type Tokens = {
  primitive: Record<string, Record<string, string>>;
  semantic: Record<string, Record<string, string>>;
  component: Record<string, string>;
};

const tokens = JSON.parse(readFileSync(join(stylesDir, 'tokens.json'), 'utf8')) as Tokens;

const REF = /^\{([a-z]+)\.([a-zA-Z0-9.-]+)\}$/;

function parseRef(value: string, allowedLayer: string, context: string): string {
  const match = REF.exec(value);
  if (!match) {
    throw new Error(`${context}: expected a {layer.path} reference, got raw value "${value}". Raw values belong in the primitive layer only.`);
  }
  const layer = match[1]!;
  const path = match[2]!;
  if (layer !== allowedLayer) {
    throw new Error(`${context}: references "${layer}" but may only reference "${allowedLayer}" (docs/design.md §4 layer rule).`);
  }
  return path;
}

// ── primitive ────────────────────────────────────────────────────────────────
const primitiveLines: string[] = [];
const primitiveNames = new Set<string>();
for (const [group, entries] of Object.entries(tokens.primitive)) {
  for (const [name, value] of Object.entries(entries)) {
    if (REF.test(value)) {
      throw new Error(`primitive.${group}.${name}: primitives must be raw values, not references.`);
    }
    const varName = `--hc-${group}-${name}`;
    primitiveNames.add(`${group}.${name}`);
    primitiveLines.push(`  ${varName}: ${value};`);
  }
}

// ── semantic (per theme) ─────────────────────────────────────────────────────
const themes = Object.keys(tokens.semantic);
if (!themes.includes('light') || !themes.includes('dark')) {
  throw new Error('tokens.json must define both "light" and "dark" semantic themes (docs/design.md §4).');
}

/** Narrows away noUncheckedIndexedAccess for a theme we already know exists. */
function themeEntries(theme: string): Record<string, string> {
  const entries = tokens.semantic[theme];
  if (!entries) throw new Error(`semantic.${theme} is not defined.`);
  return entries;
}

const semanticNames = new Set(Object.keys(themeEntries('light')));
for (const theme of themes) {
  const keys = Object.keys(themeEntries(theme));
  const missing = [...semanticNames].filter(k => !keys.includes(k));
  if (missing.length > 0) {
    throw new Error(`semantic.${theme} is missing tokens present in light: ${missing.join(', ')}. Every theme must provide the full semantic set.`);
  }
}

function renderTheme(theme: string, indent = '  '): string {
  return Object.entries(themeEntries(theme))
    .map(([name, value]) => {
      const path = parseRef(value, 'primitive', `semantic.${theme}.${name}`);
      if (!primitiveNames.has(path)) {
        throw new Error(`semantic.${theme}.${name}: unknown primitive "${path}".`);
      }
      return `${indent}--${name}: var(--hc-${path.replace('.', '-')});`;
    })
    .join('\n');
}

// ── component ────────────────────────────────────────────────────────────────
const componentLines = Object.entries(tokens.component).map(([name, value]) => {
  const path = parseRef(value, 'semantic', `component.${name}`);
  if (!semanticNames.has(path)) {
    throw new Error(`component.${name}: unknown semantic token "${path}".`);
  }
  return `  --${name}: var(--${path});`;
});

// ── emit ─────────────────────────────────────────────────────────────────────
const css = `/* GENERATED by scripts/compile-tokens.ts from src/styles/tokens.json — do not edit.
   Layer rule (docs/design.md §4): primitive -> semantic -> component. */

:root {
${primitiveLines.join('\n')}
}

/* Semantic layer. Theme variation lives here and nowhere else, keyed on
   [data-theme]. No .dark class mechanism (docs/design.md §4). */
:root,
[data-theme='light'] {
${renderTheme('light')}
}

[data-theme='dark'] {
${renderTheme('dark')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${renderTheme('dark', '    ')}
  }
}

/* Component layer — references semantic tokens only. */
:root {
${componentLines.join('\n')}
}
`;

writeFileSync(join(stylesDir, 'tokens.css'), css);
console.log(`✓ tokens.css — ${primitiveLines.length} primitive, ${semanticNames.size} semantic x ${themes.length} themes, ${componentLines.length} component`);
